- name: Upgrade kibana
  hosts: kibana
  become: true
  gather_facts: no

  tasks:
      - name: Validate ELK Version
        fail: msg="Invalid ELK Version"
        when: elk_version is undefined or not elk_version is match("\d+\.\d+\.\d+")

      - block:
            - name: Update kibana
              apt:
                  name: kibana={{ elk_version }}
                  state: present

            - name: Restart kibana
              systemd:
                  name: kibana
                  state: restarted
                  daemon_reload: yes

            - name: Wait for kibana to start listening
              wait_for:
                  port: 5601
                  delay: 5

            - name: Wait for kibana to be ready
              uri:
                  url: http://localhost:5601/api/kibana/settings
                  method: GET
                  url_username: "{{ es_username | default(omit) }}"
                  url_password: "{{ es_password | default(omit) }}"
                  headers: >-
                      {{
                        {
                          'Authorization': 'ApiKey ' + es_api_key
                        } if es_api_key is defined else omit
                      }}
                  validate_certs: false
                  force_basic_auth: "{{ false if es_api_key is defined else true }}"

              register: response
              until: "'kbn_name' in response and response.status == 200"
              retries: 30
              delay: 5

            - name: Set Default Index
              uri:
                  url: http://localhost:5601/api/kibana/settings
                  method: POST
                  url_username: "{{ es_username | default(omit) }}"
                  url_password: "{{ es_password | default(omit) }}"
                  headers: >-
                      {{
                        dict({
                          'kbn-version': elk_version,
                          'Authorization': 'ApiKey ' + es_api_key
                        }) if es_api_key is defined else {
                          'kbn-version': elk_version
                        }
                      }}
                  validate_certs: false
                  body_format: json
                  force_basic_auth: "{{ false if es_api_key is defined else true }}"
                  body: "{{ set_default_index }}"
