# File: base-with-ansible.Dockerfile
FROM eclipse-temurin:21-jre

# Install Ansible and dependencies
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    apt-add-repository --yes --update ppa:ansible/ansible && \
    apt-get install -y ansible && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
