# Start with a Node.js base image
FROM node:18-bullseye AS builder

# Install dependencies and Ansible
RUN apt-get update && \
  apt-get install -y python3 python3-pip && \
  python3 -m pip install ansible && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  apt-get install -y openssh-client && \
  pip3 install requests
